services:
  db:
    image: postgres:15-alpine
    container_name: url_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortener_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: url_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/shortener_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: replace_with_strong_access_secret_32_chars_min
      JWT_REFRESH_SECRET: replace_with_strong_refresh_secret_32_chars_min
      ACCESS_TOKEN_EXPIRE: "900"
      REFRESH_TOKEN_EXPIRE: "2592000"
    ports:
      - "8080:8080"
    command: ["sh", "-c", "sqlx migrate run && cargo run"]
  
volumes:
  postgres_data:
  redis_data: